language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
    - composer self-update
    - composer --version
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script:
  - phpunit --colors --coverage-clover=coverage.clover
  - if [ "`phpenv version-name`" = "5.5" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "`phpenv version-name`" = "5.5" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi